### ISSUE TITLE
Can't compile BCL on RedHat without pump

### ISSUE THREAD

**Issue by kimdn** [BCLCommons/bcl#9]
**Describe the bug**
![Screen Shot 2022-10-03 at 1 24 09 PM](https://user-images.githubusercontent.com/3903446/193674618-a5e8eeac-14fa-4fb0-8ea6-53917e578008.png)

**To Reproduce**
with cmake/2.8.12
./scripts/build/build_cmdline.linux.sh

**Log file**
I attach 
[CMakeOutput.log](https://github.com/BCLCommons/bcl/files/9700687/CMakeOutput.log)

and
[CMakeError.log](https://github.com/BCLCommons/bcl/files/9700692/CMakeError.log)

**Desktop (please complete the following information):**
 -Redhat OS 6.6

**Comment by roccomoretti** [comment]
I'm not sure where pump comes into it.

From the error messages, it looks like the issue is that you're attempting to use GCC 4.4.7  (`/usr/bin/gcc`) to compile things. This won't work because GCC 4.4. doesn't have C++11 support. You'll need GCC 4.8 or later (preferably GCC 5.2 or later.)

Once you've installed a more recent verison of GCC, you should be able to set the `CC` and `CXX` environment variables to tell CMake which `gcc` and `g++` executables you wish to use. (Note that this will only take effect the first time you start the compile -- you'll need to clean out the build directory first if you wish to change which compiler you're using.)

**Comment by kimdn** [comment]
After
`module load gcc/8.1.0`
./scripts/build/build_cmdline.linux.sh
has been running well. 
![Screen Shot 2022-10-03 at 2 01 09 PM](https://user-images.githubusercontent.com/3903446/193681668-93e47f19-048f-47d1-9970-ffb17b993140.png)

Thank you Rocco.

**Comment by kimdn** [comment]
After 2 hrs, the compilation is done without error.

![Screen Shot 2022-10-03 at 4 09 30 PM](https://user-images.githubusercontent.com/3903446/193701857-d2c0d042-993f-4803-ae55-233b155df8c3.png)

Unfortunately, I see a linkage error.

![Screen Shot 2022-10-03 at 4 17 28 PM](https://user-images.githubusercontent.com/3903446/193703119-8f9cb616-b70b-4d6d-a986-e642d67aa48c.png)

It is weird since this is a static build (not dynamic build).

I didn't change any environment variable (such as LD library) after I ran 
`./scripts/build/build_cmdline.linux.sh`

Even when I freshly logged into this HPC (so that .bash_profile should freshly initialize/launch), still same message.

**Comment by kimdn** [comment]
After compilation

![Screen Shot 2022-10-03 at 4 09 30 PM](https://user-images.githubusercontent.com/3903446/193704135-d596593a-89a3-42ec-abac-153d7735d85b.png)

I could run
```
/people/kimd999/ncAA_rcfs/DN/rosetta/bcl/git_repo/bcl/build/linux64_release/bin/bcl-apps-static.exe molecule:GenerateRosettaNCAAInstructions \
	-input_filenames ../input_files/phe_der.sdf \
	-output_prefix dipeptide_sdf/phe_der_out \
	-generate_3D \
	-logger File generate_dipeptides.log \
        -extra_properties ATOMATIC \
	-generate_partial_charge_file \
	-chirality auto \
        -explicit_aromaticity
```

well.

Thank you for your support.
